<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Called Fred</name>
  <uuid>fbbc17d4-f76e-46e5-9f73-5bc5e0b95873</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the name of Customer is one of { "Fred", "FRED" } 
then
	set decision to false ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
