<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>fb3e972b-1518-4dd5-a4cd-90343d24e70f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
