<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Too Young</name>
  <uuid>c3abc57d-e293-44fd-8cc4-727c75eed2d8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the age of Customer is less than 18 
then
	set decision to false ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
