<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Too Old</name>
  <uuid>695eda68-d0d7-4da9-a479-f5eb1327cf3b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the age of Customer is more than 150 
then
	set decision to false ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
